# Generated by Django 4.2.13 on 2024-05-17 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crypto",
                    models.CharField(max_length=50, verbose_name="Cryptocurrency"),
                ),
                (
                    "vs_currency",
                    models.CharField(max_length=50, verbose_name="Versus Currency"),
                ),
            ],
            options={
                "unique_together": {("crypto", "vs_currency")},
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Strategy Name"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "strategy_definition",
                    models.JSONField(verbose_name="Strategy Definition"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "final_capital",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("performance_metrics", models.JSONField(blank=True, null=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.strategy",
                    ),
                ),
                (
                    "symbols",
                    models.ManyToManyField(
                        related_name="simulations", to="simulator.symbol"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.symbol",
                    ),
                ),
            ],
            options={
                "unique_together": {("timestamp", "symbol")},
            },
        ),
    ]
