# Generated by Django 4.2.14 on 2024-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0003_action_condition_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="transactions",
            field=models.ManyToManyField(blank=True, to="simulator.transaction"),
        ),
    ]
