# Generated by Django 4.2.14 on 2024-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_remove_simulation_user_strategy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
