# Generated by Django 4.2.14 on 2024-08-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0006_strategy_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Stopped", "Stopped"),
                    ("Ready", "Ready"),
                    ("Running", "Running"),
                    ("Finished", "Finished"),
                ],
                default="Ready",
            ),
        ),
    ]
