# Generated by Django 5.1.1 on 2024-09-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_remove_condition_actions_condition_condition_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='simulator.conditiongroup'),
        ),
    ]
