# Generated by Django 4.2.15 on 2024-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0007_simulation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
