# Generated by Django 4.2.15 on 2024-09-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0008_simulation_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeFrame",
            fields=[
                (
                    "timeframe_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="close_price",
            new_name="close",
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="high_price",
            new_name="high",
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="low_price",
            new_name="low",
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="open_price",
            new_name="open",
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="symbol",
            new_name="pair",
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="symbol",
            name="base_currency",
            field=models.CharField(default="BTC", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="symbol",
            name="quote_currency",
            field=models.CharField(default="USDT", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together={("base_currency", "quote_currency")},
        ),
        migrations.AddField(
            model_name="pricedata",
            name="timeframe",
            field=models.ForeignKey(
                default="1m",
                on_delete=django.db.models.deletion.CASCADE,
                to="simulator.timeframe",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="pricedata",
            index=models.Index(
                fields=["pair", "timeframe", "timestamp"],
                name="simulator_p_pair_id_c55d54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="symbol",
            index=models.Index(
                fields=["base_currency", "quote_currency"],
                name="simulator_s_base_cu_b10659_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricedata",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="crypto",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="vs_currency",
        ),
        migrations.AlterUniqueTogether(
            name="pricedata",
            unique_together={("pair", "timeframe", "timestamp")},
        ),
    ]
