# Generated by Django 5.1.1 on 2024-09-27 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_alter_condition_condition_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='position',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='position',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='position',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='position',
            name='initial_size',
            field=models.DecimalField(decimal_places=10, default=100, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='position',
            name='realized_profit',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='stop_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='take_profit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='total_profit',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_profit',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='fee',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
    ]
