# Generated by Django 5.1.1 on 2024-09-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0009_remove_position_is_closed_remove_position_profit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="initial_size",
        ),
    ]
