# Generated by Django 4.2.16 on 2024-09-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_simulation_data_end_date_simulation_data_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalindicator',
            name='price',
        ),
        migrations.AddField(
            model_name='technicalindicator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                      verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricedata',
            name='technical_indicator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulator.technicalindicator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='simulator.symbol'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.timeframe'),
        ),
    ]
