# Generated by Django 4.2.16 on 2024-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0013_alter_pricedata_technical_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="comparison_indicator",
            field=models.CharField(
                blank=True,
                choices=[("MACD", "MACD"), ("PRICE", "Price"), ("RSI", "RSI")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="type",
            field=models.CharField(
                choices=[("BUY", "BUY"), ("SELL", "SELL")], default="BUY", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="condition",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
