# Generated by Django 4.2.16 on 2024-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0014_condition_comparison_indicator_condition_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="comparison_indicator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACD", "MACD"),
                    ("PRICE", "Price"),
                    ("RSI", "RSI"),
                    ("MA20", "MA20"),
                    ("MA50", "MA50"),
                    ("MA100", "MA100"),
                    ("MA200", "MA200"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="indicator",
            field=models.CharField(
                choices=[
                    ("MACD", "MACD"),
                    ("PRICE", "Price"),
                    ("RSI", "RSI"),
                    ("MA20", "MA20"),
                    ("MA50", "MA50"),
                    ("MA100", "MA100"),
                    ("MA200", "MA200"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="operator",
            field=models.CharField(
                choices=[
                    (">=", "Greater than or equal to"),
                    ("<=", "Less than or equal to"),
                    ("==", "Equal to"),
                    ("<", "Less than"),
                    (">", "Greater than"),
                    ("CROSSOVER", "Crossover"),
                ],
                max_length=10,
            ),
        ),
    ]
