# Generated by Django 5.1.1 on 2024-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0014_alter_technicalindicator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='current_price',
            field=models.BooleanField(default=False),
        ),
    ]
