# Generated by Django 4.2.16 on 2024-09-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0016_condition_crossover_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="actions",
            field=models.ManyToManyField(blank=True, null=True, to="simulator.action"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="parameters",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Strategy Parameters"
            ),
        ),
    ]
