# Generated by Django 4.2.16 on 2024-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0017_alter_strategy_actions_alter_strategy_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalindicator",
            name="ma100",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="technicalindicator",
            name="ma20",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="technicalindicator",
            name="ma200",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="technicalindicator",
            name="ma50",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
