# Generated by Django 4.2.16 on 2024-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0018_technicalindicator_ma100_technicalindicator_ma20_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricedata",
            name="technical_indicator",
        ),
        migrations.AddField(
            model_name="pricedata",
            name="bollinger_lower",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="bollinger_upper",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="ema_20",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="ma100",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="ma20",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="ma200",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="ma50",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="macd",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="macd_signal",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="rsi_14",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricedata",
            name="sma_20",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.DeleteModel(
            name="TechnicalIndicator",
        ),
    ]
