# Generated by Django 5.1.1 on 2024-09-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0019_remove_pricedata_technical_indicator_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricedata",
            old_name="ma100",
            new_name="sma_100",
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="ma20",
            new_name="sma_200",
        ),
        migrations.RenameField(
            model_name="pricedata",
            old_name="ma50",
            new_name="sma_50",
        ),
        migrations.RemoveField(
            model_name="pricedata",
            name="ma200",
        ),
    ]
