export const STRATEGY = {
  LIST_REQUEST: 'STRATEGY_LIST_REQUEST',
  LIST_SUCCESS: 'STRATEGY_LIST_SUCCESS',
  LIST_FAIL: 'STRATEGY_LIST_FAIL',

  DETAILS_REQUEST: 'STRATEGY_DETAILS_REQUEST',
  DETAILS_SUCCESS: 'STRATEGY_DETAILS_SUCCESS',
  DETAILS_FAIL: 'STRATEGY_DETAILS_FAIL',

  CREATE_REQUEST: 'STRATEGY_CREATE_REQUEST',
  CREATE_SUCCESS: 'STRATEGY_CREATE_SUCCESS',
  CREATE_FAIL: 'STRATEGY_CREATE_FAIL',
  CREATE_RESET: 'STRATEGY_CREATE_RESET',

  UPDATE_REQUEST: 'STRATEGY_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'STRATEGY_UPDATE_SUCCESS',
  UPDATE_FAIL: 'STRATEGY_UPDATE_FAIL',
  UPDATE_RESET: 'STRATEGY_UPDATE_RESET',

  DELETE_REQUEST: 'STRATEGY_DELETE_REQUEST',
  DELETE_SUCCESS: 'STRATEGY_DELETE_SUCCESS',
  DELETE_FAIL: 'STRATEGY_DELETE_FAIL',
  DELETE_RESET: 'STRATEGY_DELETE_RESET',
};

export const SIMULATION = {
  LIST_REQUEST: 'SIMULATION_LIST_REQUEST',
  LIST_SUCCESS: 'SIMULATION_LIST_SUCCESS',
  LIST_FAIL: 'SIMULATION_LIST_FAIL',

  DETAILS_REQUEST: 'SIMULATION_DETAILS_REQUEST',
  DETAILS_SUCCESS: 'SIMULATION_DETAILS_SUCCESS',
  DETAILS_FAIL: 'SIMULATION_DETAILS_FAIL',

  SUMMARY_REQUEST: 'SIMULATION_SUMMARY_REQUEST',
  SUMMARY_SUCCESS: 'SIMULATION_SUMMARY_SUCCESS',
  SUMMARY_FAIL: 'SIMULATION_SUMMARY_FAIL',

  CREATE_REQUEST: 'SIMULATION_CREATE_REQUEST',
  CREATE_SUCCESS: 'SIMULATION_CREATE_SUCCESS',
  CREATE_FAIL: 'SIMULATION_CREATE_FAIL',
  CREATE_RESET: 'SIMULATION_CREATE_RESET'
};

export const USER = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',

  LOGOUT: 'USER_LOGOUT',
};
