export const STRATEGY_LIST_REQUEST = 'STRATEGY_LIST_REQUEST'
export const STRATEGY_LIST_SUCCESS = 'STRATEGY_LIST_SUCCESS'
export const STRATEGY_LIST_FAIL = 'STRATEGY_LIST_FAIL'

export const STRATEGY_DETAILS_REQUEST = 'STRATEGY_DETAILS_REQUEST'
export const STRATEGY_DETAILS_SUCCESS = 'STRATEGY_DETAILS_SUCCESS'
export const STRATEGY_DETAILS_FAIL = 'STRATEGY_DETAILS_FAIL'

export const SIMULATION_LIST_REQUEST = 'SIMULATION_LIST_REQUEST'
export const SIMULATION_LIST_SUCCESS = 'SIMULATION_LIST_SUCCESS'
export const SIMULATION_LIST_FAIL = 'SIMULATION_LIST_FAIL'

export const SIMULATION_DETAILS_REQUEST = 'SIMULATION_DETAILS_REQUEST'
export const SIMULATION_DETAILS_SUCCESS = 'SIMULATION_DETAILS_SUCCESS'
export const SIMULATION_DETAILS_FAIL = 'SIMULATION_DETAILS_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
